dsn: mysql://kratos:kratos@tcp(mysql:3306)/kratos
identity:
  schemas:
  - id: default
    url: file:///home/kratos/schemas/default.json
selfservice:
  default_browser_return_url: http://192.168.0.53:4433
