name: kratos

volumes:
  data:

networks:
  backend:

services:
  mysql:
    image: mysql:latest
    volumes:
    - data:/var/lib/mysql
    networks:
    - backend
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: kratos
      MYSQL_USER: kratos
      MYSQL_PASSWORD: kratos

  kratos:
    image: thunderball/kratos:v1.3.1
    command: serve --config /home/kratos/config.yml
    read_only: true
    volumes:
    - ./config/kratos:/home/kratos:ro
    networks:
    - backend
    ports:
    - 4433:4433/tcp
    # - 4434:4434/tcp # Admin port not exposed
